# .github/workflows/docker-build-and-push.yml
name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/screenshot-to-code-backend
      FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/screenshot-to-code-front

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend image
      - name: Build and push backend Docker image
        working-directory: ./backend
        run: |
          docker build -t $BACKEND_IMAGE:latest .
          docker push $BACKEND_IMAGE:latest

      # Build and push frontend image
      - name: Build and push frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t $FRONTEND_IMAGE:latest .
          docker push $FRONTEND_IMAGE:latest
